apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-back
  template:
    metadata:
      labels:
        app: my-app-back
    spec:
      containers:
      - name: my-app-back
        image: mariomafdy/backend:latest
        ports:
        - containerPort: 7000
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: password
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb://admin:password@mongodb:27017
        # - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secret
        #       key: mongo-root-username
        # - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        #   valueFrom: 
        #     secretKeyRef:
        #       name: mongodb-secret
        #       key: mongo-root-password
        # - name: ME_CONFIG_MONGODB_SERVER
        #   valueFrom: 
        #     configMapKeyRef:
        #       name: mongodb-configmap
        #       key: database_url
        # - name: ME_CONFIG_MONGODB_URI
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mongodb-configmap
        #       key: connection_uri